apiVersion: v1
kind: Pod
metadata:
  name: readiness-exemplo
spec:
  containers:
    - name: app
      image: nginx:1.25
      ports:
        - containerPort: 80
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10