apiVersion: v1
kind: ResourceQuota

metadata:
  name: homolog-quota
  namespace: homolog

spec:
  hard:
    pods: "20"

    requests.cpu: "2"
    requests.memory: "2Gi"

    limits.cpu: "4"
    limits.memory: "4Gi"